In [3]:
import numpy as np

In [4]:
a=[1,2,3,4]
b=[5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
[a[i]+b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [11]:
import numpy as np
a=np.array([1,3,3,4])
b=np.array([8,6,7,8])
a+b

array([ 9,  9, 10, 12])

In [14]:
np.array([1,2,3])

array([1, 2, 3])

In [15]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr[:,:1]

array([[1],
       [4],
       [7]])

In [23]:
arr[0:1]

array([[1, 2, 3]])

In [24]:
arr[1:1]

array([], shape=(0, 3), dtype=int32)

In [25]:
arr[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [26]:
arr[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [29]:
arr[:1,:2]

array([[1, 2]])

In [30]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [39]:
arr[1:,::2]

array([[4, 6],
       [7, 9]])

In [42]:
arr[2:,:3]

array([[7, 8, 9]])

In [43]:
np.eye(3,3).astype("int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [44]:
np.eye(3,3).dtype

dtype('float64')

In [47]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [52]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [54]:
np.arange(3,25,4)

array([ 3,  7, 11, 15, 19, 23])

In [55]:
a[a>2]

array([3, 3, 4])

In [58]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [68]:
np.linspace(1,18,5)

array([ 1.  ,  5.25,  9.5 , 13.75, 18.  ])

In [10]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [11]:
import numpy as np 
a=np.array([1,2,3])
a+2

array([3, 4, 5])

In [12]:
a*3

array([3, 6, 9])

In [13]:
a**2

array([1, 4, 9])

In [16]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [17]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [18]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [21]:
np.linalg.det(a)

-9.51619735392994e-16

In [22]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [23]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [24]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
a=np.array([1,2,3,4,5,6,6,7,8,9,1,2])
a

array([1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 1, 2])

In [28]:
len(a)

12

In [29]:
np.reshape(np.reshape(a,(3,4)),(6,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [6, 7],
       [8, 9],
       [1, 2]])

In [30]:
b=np.resize(a,(3,4))

In [31]:
b

array([[1, 2, 3, 4],
       [5, 6, 6, 7],
       [8, 9, 1, 2]])

In [32]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([6, 7, 8, 9, 1, 2])]

In [33]:
np.split(a,3)

[array([1, 2, 3, 4]), array([5, 6, 6, 7]), array([8, 9, 1, 2])]

In [34]:
np.split(a,4)

[array([1, 2, 3]), array([4, 5, 6]), array([6, 7, 8]), array([9, 1, 2])]

In [35]:
np.split(a,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([6, 7]),
 array([8, 9]),
 array([1, 2])]