In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(a,axis=0)

array([12, 15, 18])

In [5]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [6]:
def mean(array):
    n=len(array)
    return np.sum(array)/n

In [9]:
mean(np.array([1,2,3,4,5,6]))

3.5

In [23]:
def variance(array):
    n=len(array)
    m=mean(array)
    return np.sum((array-m)**2)/n

In [24]:
variance(np.array([1,2,3,4,5,6]))

2.9166666666666665

In [53]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
min_vals=arr.min(axis=0)
max_vals=arr.max(axis=0)
scalar_data=(arr-min_vals)/(max_vals-min_vals)

In [54]:
print("scaled data:\n",scalar_data)

scaled data:
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [57]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
mean=np.mean(arr,axis=0)
std=np.std(arr,axis=0)
scalar=(arr-mean)/(std)

In [58]:
print(scalar)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
